# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxjAKRxA8VXbyhZCQtjNPljo-D-WtOTV

**Import the Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**Load the Dataset**"""

df=pd.read_csv('/content/netflix_titles (1).csv')

"""**Preview of the Dataset**"""

df.head()

"""**Other Details about the Dataset**"""

df.shape

df.columns

df.info()

df.index

"""**Checking for missing values**"""

df.isnull().sum()

df[df.duplicated()]

"""*The above cells indicate that there is no duplicate values in the dataset. It contains only null values*"""

df.shape

"""**Data Cleaning**"""

df.drop_duplicates(inplace=True) #dropping duplicates

df.shape #No duplicates in the dataset

df.dropna(inplace=True) #dropping null values

df.shape #nullvalues were removed

df.dropna(subset=['director', 'cast', 'country'],how='any',inplace=True) #drop rows with missing necessary information

df.shape

df['date_added']=pd.to_datetime(df['date_added'],format='mixed') #convert 'date_added' to datetime

df.head(2) #The values have changed

"""**Exploratory Data Analysis(EDA)**"""

content=df['type'].value_counts()
content

plt.figure(figsize=(10,5))
sns.histplot(df,x=df['type'])
plt.title('Types of Content')

plt.pie(content,labels=['Movies','TV Series'],autopct='%.0f%%')
plt.title('Content on Netflix')

df.head(1)

yr=df['release_year'].value_counts().reset_index().sort_values(by='count',ascending=False)[:10]
yr

plt.bar(yr['release_year'],yr['count'])
plt.title('Top 10 years with the most content releases')

rv=df['rating'].value_counts()

ratings=df['rating'].value_counts().reset_index().sort_values(by='count',ascending=False)
ratings

fig,axs=plt.subplots(nrows=1,ncols=2, figsize=(11,6))
axs[1].pie(ratings['count'][:8],autopct='%.0f%%',labels=ratings['rating'][:8])
axs[0].bar(ratings['rating'],ratings['count'])
axs[0].tick_params(axis='x',rotation=45)
plt.suptitle('Ratings on Netflix')

top10countries=df['country'].value_counts().reset_index().sort_values(by='count',ascending=False)[:10]
top10countries

plt.figure(figsize=(10,5))
plt.bar(top10countries['country'],top10countries['count'])
plt.xticks(rotation=45)
plt.title('Top 10 countries with most content on Netflix')

df['year']=df['date_added'].dt.year
df['month']=df['date_added'].dt.month
df['day']=df['date_added'].dt.day

df.head(2)

top10dir=df['director'].value_counts().reset_index().sort_values(by='count',ascending=False)[:10]
top10dir

plt.figure(figsize=(10,5))
plt.bar(top10dir['director'],top10dir['count'])
plt.xticks(rotation=45)
plt.title('Top 10 directors with most content on Netflix')

sns.countplot(y="rating", data=df, hue="type", palette=["#E50914","#221F1F"])
plt.show()